/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import javax.swing.JLabel;

/**
 *
 * @author gabri
 */
public class ActivitiesView extends javax.swing.JInternalFrame {
    /**
     * Creates new form ActivitiesView
     */
    public ActivitiesView() {
        initComponents();
        this.labelWordShowed.setText("");
    }

    public JLabel getLabelImage() {
        return labelImage;
    }

    public void setLabelImage(JLabel labelImage) {
        this.labelImage = labelImage;
    }

    public JLabel getLabelWordShowed() {
        return labelWordShowed;
    }

    public void setLabelWordShowed(JLabel labelWordShowed) {
        this.labelWordShowed = labelWordShowed;
    }

    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelImage = new javax.swing.JLabel();
        labelWordShowed = new javax.swing.JLabel();

        setMaximizable(true);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        labelImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/resources/noimage.png"))); // NOI18N

        labelWordShowed.setFont(new java.awt.Font("Tahoma", 1, 300)); // NOI18N
        labelWordShowed.setForeground(new java.awt.Color(255, 0, 0));
        labelWordShowed.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labelWordShowed.setText("REI");
        labelWordShowed.setToolTipText("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelWordShowed, javax.swing.GroupLayout.PREFERRED_SIZE, 626, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(labelImage, javax.swing.GroupLayout.PREFERRED_SIZE, 570, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(labelImage))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(152, 152, 152)
                        .addComponent(labelWordShowed, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        setBounds(0, 0, 1255, 596);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel labelImage;
    private javax.swing.JLabel labelWordShowed;
    // End of variables declaration//GEN-END:variables
}
