/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.util.List;
import javax.swing.ImageIcon;

/**
 *
 * @author gabri
 */
public class ActivitiesView extends javax.swing.JInternalFrame {
    private MainWindow mainWindow;
    private List<String> wordsForActivity;
    private int pageNow;
    /**
     * Creates new form ActivitiesView
     */
    public ActivitiesView(MainWindow m, List<String> wordsList) {
        initComponents();
        this.mainWindow = m;
        this.wordsForActivity = wordsList;
        this.pageNow = 1;
        this.buttonPrevious.setEnabled(false);
        
        labelImage.setIcon(new ImageIcon(getClass().getResource("/view/imagens/" + wordsForActivity.get(pageNow-1) + ".png")));
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelImage = new javax.swing.JLabel();
        buttonNext = new javax.swing.JButton();
        buttonPrevious = new javax.swing.JButton();

        setMaximizable(true);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        labelImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagens/rei.png"))); // NOI18N

        buttonNext.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/resources/next.png"))); // NOI18N
        buttonNext.setToolTipText("");
        buttonNext.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        buttonNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonNextActionPerformed(evt);
            }
        });

        buttonPrevious.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/resources/previous.png"))); // NOI18N
        buttonPrevious.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        buttonPrevious.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonPreviousActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(buttonPrevious)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 140, Short.MAX_VALUE)
                .addComponent(buttonNext)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(labelImage, javax.swing.GroupLayout.PREFERRED_SIZE, 414, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(buttonPrevious)
                    .addComponent(buttonNext)
                    .addComponent(labelImage))
                .addContainerGap(38, Short.MAX_VALUE))
        );

        setBounds(0, 0, 750, 605);
    }// </editor-fold>//GEN-END:initComponents

    private void buttonNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonNextActionPerformed
        this.pageNow++;
        labelImage.setIcon(new ImageIcon(getClass().getResource("/view/imagens/" + wordsForActivity.get(pageNow-1) + ".png")));
        if(this.pageNow == this.wordsForActivity.size()){
            this.buttonNext.setEnabled(false);
        }
        this.buttonPrevious.setEnabled(true);        
    }//GEN-LAST:event_buttonNextActionPerformed

    private void buttonPreviousActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonPreviousActionPerformed
        this.pageNow--;
        labelImage.setIcon(new ImageIcon(getClass().getResource("/view/imagens/" + wordsForActivity.get(pageNow-1) + ".png")));
        if(this.pageNow == 1){
            this.buttonPrevious.setEnabled(false);
        }
        this.buttonNext.setEnabled(true);
    }//GEN-LAST:event_buttonPreviousActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonNext;
    private javax.swing.JButton buttonPrevious;
    private javax.swing.JLabel labelImage;
    // End of variables declaration//GEN-END:variables
}
