/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

/**
 *
 * @author gabri
 */
public class AnagramView extends javax.swing.JInternalFrame {

    /**
     * Creates new form AnagramView
     */
    public AnagramView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToggleButton4 = new javax.swing.JToggleButton();
        jToggleButton12 = new javax.swing.JToggleButton();
        panelForWord = new javax.swing.JPanel();
        labelWordFormed = new javax.swing.JLabel();
        buttonLetter1 = new javax.swing.JToggleButton();
        buttonLetter2 = new javax.swing.JToggleButton();
        buttonLetter3 = new javax.swing.JToggleButton();
        buttonLetter4 = new javax.swing.JToggleButton();
        buttonLetter5 = new javax.swing.JToggleButton();
        buttonLetter6 = new javax.swing.JToggleButton();
        buttonLetter7 = new javax.swing.JToggleButton();
        buttonLetter8 = new javax.swing.JToggleButton();
        buttonLetter9 = new javax.swing.JToggleButton();
        buttonLetter10 = new javax.swing.JToggleButton();
        buttonLetter11 = new javax.swing.JToggleButton();

        jToggleButton4.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jToggleButton4.setText("G");

        jToggleButton12.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jToggleButton12.setText("G");

        setMaximizable(true);
        setResizable(true);

        panelForWord.setBackground(new java.awt.Color(0, 102, 102));

        labelWordFormed.setBackground(new java.awt.Color(255, 255, 255));
        labelWordFormed.setFont(new java.awt.Font("Tahoma", 1, 90)); // NOI18N
        labelWordFormed.setForeground(new java.awt.Color(204, 204, 204));
        labelWordFormed.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelWordFormed.setText("PALAVRA FORMADA AQUI");
        labelWordFormed.setToolTipText("");

        javax.swing.GroupLayout panelForWordLayout = new javax.swing.GroupLayout(panelForWord);
        panelForWord.setLayout(panelForWordLayout);
        panelForWordLayout.setHorizontalGroup(
            panelForWordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelForWordLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelWordFormed, javax.swing.GroupLayout.DEFAULT_SIZE, 1219, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelForWordLayout.setVerticalGroup(
            panelForWordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelForWordLayout.createSequentialGroup()
                .addGap(185, 185, 185)
                .addComponent(labelWordFormed, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(139, Short.MAX_VALUE))
        );

        buttonLetter1.setFont(new java.awt.Font("Tahoma", 1, 55)); // NOI18N
        buttonLetter1.setText("G");
        buttonLetter1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        buttonLetter2.setFont(new java.awt.Font("Tahoma", 1, 55)); // NOI18N
        buttonLetter2.setText("G");
        buttonLetter2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        buttonLetter3.setFont(new java.awt.Font("Tahoma", 1, 55)); // NOI18N
        buttonLetter3.setText("G");
        buttonLetter3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        buttonLetter4.setFont(new java.awt.Font("Tahoma", 1, 55)); // NOI18N
        buttonLetter4.setText("G");
        buttonLetter4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        buttonLetter5.setFont(new java.awt.Font("Tahoma", 1, 55)); // NOI18N
        buttonLetter5.setText("G");
        buttonLetter5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        buttonLetter6.setFont(new java.awt.Font("Tahoma", 1, 55)); // NOI18N
        buttonLetter6.setText("G");
        buttonLetter6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        buttonLetter7.setFont(new java.awt.Font("Tahoma", 1, 55)); // NOI18N
        buttonLetter7.setText("G");
        buttonLetter7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        buttonLetter8.setFont(new java.awt.Font("Tahoma", 1, 55)); // NOI18N
        buttonLetter8.setText("G");
        buttonLetter8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        buttonLetter9.setFont(new java.awt.Font("Tahoma", 1, 55)); // NOI18N
        buttonLetter9.setText("G");
        buttonLetter9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        buttonLetter10.setFont(new java.awt.Font("Tahoma", 1, 55)); // NOI18N
        buttonLetter10.setText("G");
        buttonLetter10.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        buttonLetter11.setFont(new java.awt.Font("Tahoma", 1, 55)); // NOI18N
        buttonLetter11.setText("G");
        buttonLetter11.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelForWord, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(115, 115, 115)
                .addComponent(buttonLetter1)
                .addGap(18, 18, 18)
                .addComponent(buttonLetter2)
                .addGap(18, 18, 18)
                .addComponent(buttonLetter3)
                .addGap(18, 18, 18)
                .addComponent(buttonLetter4)
                .addGap(18, 18, 18)
                .addComponent(buttonLetter5)
                .addGap(18, 18, 18)
                .addComponent(buttonLetter6)
                .addGap(18, 18, 18)
                .addComponent(buttonLetter7)
                .addGap(18, 18, 18)
                .addComponent(buttonLetter8)
                .addGap(18, 18, 18)
                .addComponent(buttonLetter9)
                .addGap(18, 18, 18)
                .addComponent(buttonLetter10)
                .addGap(18, 18, 18)
                .addComponent(buttonLetter11)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelForWord, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonLetter1)
                    .addComponent(buttonLetter2)
                    .addComponent(buttonLetter3)
                    .addComponent(buttonLetter4)
                    .addComponent(buttonLetter5)
                    .addComponent(buttonLetter6)
                    .addComponent(buttonLetter7)
                    .addComponent(buttonLetter8)
                    .addComponent(buttonLetter9)
                    .addComponent(buttonLetter10)
                    .addComponent(buttonLetter11))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        setBounds(0, 0, 1255, 596);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton buttonLetter1;
    private javax.swing.JToggleButton buttonLetter10;
    private javax.swing.JToggleButton buttonLetter11;
    private javax.swing.JToggleButton buttonLetter2;
    private javax.swing.JToggleButton buttonLetter3;
    private javax.swing.JToggleButton buttonLetter4;
    private javax.swing.JToggleButton buttonLetter5;
    private javax.swing.JToggleButton buttonLetter6;
    private javax.swing.JToggleButton buttonLetter7;
    private javax.swing.JToggleButton buttonLetter8;
    private javax.swing.JToggleButton buttonLetter9;
    private javax.swing.JToggleButton jToggleButton12;
    private javax.swing.JToggleButton jToggleButton4;
    private javax.swing.JLabel labelWordFormed;
    private javax.swing.JPanel panelForWord;
    // End of variables declaration//GEN-END:variables
}
