/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.applet.Applet;
import java.applet.AudioClip;
import java.awt.Color;
import java.net.URL;
import java.util.ArrayList;
import java.util.Collections;
import java.util.List;
import javax.swing.ImageIcon;

/**
 *
 * @author Gabriel Stahlberg
 */
public class GuessView extends javax.swing.JInternalFrame {

    private MainWindow mainWindow;
    private List<String> wordsList;
    private int pageNow;
    private String wordToGuess;
    private AudioClip sound;
    private int max;

    /**
     * Creates new form GuessView
     */
    public GuessView(MainWindow m) {
        initComponents();
        this.mainWindow = m;
        this.wordsList = this.mainWindow.getWordsForGuess();
        this.pageNow = 1;
        this.max = this.mainWindow.getWordsForActivity().size();
        this.buttonPrevious.setEnabled(false);
        adjustComponents();
    }

    private void adjustButtons() {
        this.mainWindow.getButtonNext().setEnabled(true);
        this.mainWindow.getButtonPrevious().setEnabled(true);
        this.mainWindow.getButtonShowImage().setEnabled(true);
        this.mainWindow.getButtonShowWord().setEnabled(true);
        this.mainWindow.getButtonShowWord2().setEnabled(true);
        this.mainWindow.getButtonAnagram().setEnabled(true);
        this.mainWindow.getButtonGuess().setEnabled(true);
        this.mainWindow.getButtonSound().setEnabled(true);
    }

    private void adjustComponents() {
        List<String> wordsAleatory = new ArrayList<>(3);
        List<String> listAux = new ArrayList<>(9);
        String word = this.wordsList.get(this.pageNow - 1);
        this.labelImage.setIcon(new ImageIcon(getClass().getResource("/view/imagensB/" + word.toLowerCase() + ".png")));
        wordsAleatory.add(word);
        this.wordToGuess = word;

        this.wordsList.forEach((wordNow) -> {
            listAux.add(wordNow);
        });

        do {
            Collections.shuffle(listAux);
            if (!listAux.get(0).equals(word)) {
                wordsAleatory.add(listAux.remove(0));
            }
        } while (wordsAleatory.size() != 3);

        Collections.shuffle(wordsAleatory);

        this.labelWord1.setText(wordsAleatory.get(0));
        this.labelWord2.setText(wordsAleatory.get(1));
        this.labelWord3.setText(wordsAleatory.get(2));
    }

    private void setDisableButtons() {
        this.buttonWord1.setEnabled(false);
        this.buttonWord2.setEnabled(false);
        this.buttonWord3.setEnabled(false);
    }
    private void setEnableButtons() {
        this.buttonWord1.setEnabled(true);
        this.buttonWord2.setEnabled(true);
        this.buttonWord3.setEnabled(true);
        
        this.labelWord1.setForeground(Color.black);
        this.labelWord2.setForeground(Color.black);
        this.labelWord3.setForeground(Color.black);
    }
    

    private void startSound() {
        URL wow = MainWindow.class.getResource("resources/wow.wav");
        this.sound = Applet.newAudioClip(wow);
        this.sound.play();

        URL palmas = MainWindow.class.getResource("resources/palmas.wav");
        this.sound = Applet.newAudioClip(palmas);
        this.sound.play();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonWord1 = new javax.swing.JButton();
        buttonWord2 = new javax.swing.JButton();
        buttonWord3 = new javax.swing.JButton();
        labelImage = new javax.swing.JLabel();
        labelWord1 = new javax.swing.JLabel();
        labelWord3 = new javax.swing.JLabel();
        labelWord2 = new javax.swing.JLabel();
        buttonReturn = new javax.swing.JButton();
        buttonPrevious = new javax.swing.JButton();
        buttonNext = new javax.swing.JButton();

        setMaximizable(true);
        setResizable(true);

        buttonWord1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/resources/finger.png"))); // NOI18N
        buttonWord1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        buttonWord1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonWord1ActionPerformed(evt);
            }
        });

        buttonWord2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/resources/finger.png"))); // NOI18N
        buttonWord2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        buttonWord2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonWord2ActionPerformed(evt);
            }
        });

        buttonWord3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/resources/finger.png"))); // NOI18N
        buttonWord3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        buttonWord3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonWord3ActionPerformed(evt);
            }
        });

        labelImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagensB/amor-perfeito.png"))); // NOI18N
        labelImage.setText("jLabel3");

        labelWord1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        labelWord1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labelWord1.setText("AMOR-PERFEITO");
        labelWord1.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        labelWord3.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        labelWord3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labelWord3.setText("AMOR-PERFEITO");
        labelWord3.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        labelWord2.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        labelWord2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labelWord2.setText("AMOR-PERFEITO");
        labelWord2.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        buttonReturn.setBackground(new java.awt.Color(102, 102, 102));
        buttonReturn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/resources/return.png"))); // NOI18N
        buttonReturn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        buttonReturn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonReturnActionPerformed(evt);
            }
        });

        buttonPrevious.setBackground(new java.awt.Color(102, 102, 102));
        buttonPrevious.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/resources/previous.png"))); // NOI18N
        buttonPrevious.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        buttonPrevious.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonPreviousActionPerformed(evt);
            }
        });

        buttonNext.setBackground(new java.awt.Color(102, 102, 102));
        buttonNext.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/resources/next.png"))); // NOI18N
        buttonNext.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        buttonNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonNextActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(buttonReturn, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(buttonWord3)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(labelWord3, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(buttonWord1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(labelWord1, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(buttonWord2)
                            .addGap(37, 37, 37)
                            .addComponent(labelWord2, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 118, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelImage, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(buttonPrevious, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(buttonNext, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(68, 68, 68))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(labelImage, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(buttonPrevious)
                            .addComponent(buttonNext)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(buttonReturn, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(97, 97, 97)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(buttonWord1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(labelWord1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(labelWord2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(buttonWord2))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(buttonWord3, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(labelWord3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        setBounds(0, 0, 1255, 596);
    }// </editor-fold>//GEN-END:initComponents

    private void buttonReturnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonReturnActionPerformed
        this.setVisible(false);
        this.mainWindow.getDesktop().add(this.mainWindow.getMv().getAv());
        adjustButtons();
    }//GEN-LAST:event_buttonReturnActionPerformed

    private void buttonPreviousActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonPreviousActionPerformed
        this.pageNow--;
        adjustComponents();
        setEnableButtons();
        if (this.pageNow == 1) {
            this.buttonPrevious.setEnabled(false);
        }
        this.buttonNext.setEnabled(true);
    }//GEN-LAST:event_buttonPreviousActionPerformed

    private void buttonNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonNextActionPerformed
        this.buttonPrevious.setEnabled(true);
        this.pageNow++;
        adjustComponents();
        setEnableButtons();
        if (this.max == this.pageNow) {
            this.buttonNext.setEnabled(false);
        }
    }//GEN-LAST:event_buttonNextActionPerformed

    private void buttonWord1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonWord1ActionPerformed
        if (this.labelWord1.getText().equals(this.wordToGuess)) {
            this.labelWord1.setForeground(Color.green);
            startSound();
        } else {
            this.labelWord1.setForeground(Color.red);
        }
        setDisableButtons();
    }//GEN-LAST:event_buttonWord1ActionPerformed

    private void buttonWord2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonWord2ActionPerformed
        if (this.labelWord2.getText().equals(this.wordToGuess)) {
            this.labelWord2.setForeground(Color.green);
            startSound();
        } else {
            this.labelWord2.setForeground(Color.red);
        }
        setDisableButtons();
    }//GEN-LAST:event_buttonWord2ActionPerformed

    private void buttonWord3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonWord3ActionPerformed
        if (this.labelWord3.getText().equals(this.wordToGuess)) {
            this.labelWord3.setForeground(Color.green);
            startSound();
        } else {
            this.labelWord3.setForeground(Color.red);
        }
        setDisableButtons();
    }//GEN-LAST:event_buttonWord3ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonNext;
    private javax.swing.JButton buttonPrevious;
    private javax.swing.JButton buttonReturn;
    private javax.swing.JButton buttonWord1;
    private javax.swing.JButton buttonWord2;
    private javax.swing.JButton buttonWord3;
    private javax.swing.JLabel labelImage;
    private javax.swing.JLabel labelWord1;
    private javax.swing.JLabel labelWord2;
    private javax.swing.JLabel labelWord3;
    // End of variables declaration//GEN-END:variables
}
