/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

/**
 *
 * @author Gabriel Stahlberg
 */
public class GuessView extends javax.swing.JInternalFrame {
    private MainWindow mainWindow;
    /**
     * Creates new form GuessView
     */
    public GuessView(MainWindow m) {
        initComponents();
        this.mainWindow = m;
    }
    
    private void adjustButtons(){
        this.mainWindow.getButtonNext().setEnabled(true);
        this.mainWindow.getButtonPrevious().setEnabled(true);
        this.mainWindow.getButtonShowImage().setEnabled(true);
        this.mainWindow.getButtonShowWord().setEnabled(true);
        this.mainWindow.getButtonAlert().setEnabled(true);
        this.mainWindow.getButtonAnagram().setEnabled(true);
        this.mainWindow.getButtonGuess().setEnabled(true);
        this.mainWindow.getButtonSound().setEnabled(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        buttonWord1 = new javax.swing.JButton();
        buttonWord2 = new javax.swing.JButton();
        buttonWord3 = new javax.swing.JButton();
        labelImage = new javax.swing.JLabel();
        labelWord1 = new javax.swing.JLabel();
        labelWord3 = new javax.swing.JLabel();
        labelWord2 = new javax.swing.JLabel();
        buttonReturn = new javax.swing.JButton();

        setMaximizable(true);
        setResizable(true);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 40)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(53, 44, 200));
        jLabel1.setText("QUAL DESSAS PALAVRAS");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 40)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(53, 44, 200));
        jLabel2.setText("CORRESPONDE À IMAGEM:");

        buttonWord1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/resources/finger.png"))); // NOI18N
        buttonWord1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        buttonWord2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/resources/finger.png"))); // NOI18N
        buttonWord2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        buttonWord3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/resources/finger.png"))); // NOI18N
        buttonWord3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        labelImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagensB/amor-perfeito.png"))); // NOI18N
        labelImage.setText("jLabel3");

        labelWord1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        labelWord1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelWord1.setText("AMOR-PERFEITO");
        labelWord1.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        labelWord3.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        labelWord3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelWord3.setText("AMOR-PERFEITO");
        labelWord3.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        labelWord2.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        labelWord2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelWord2.setText("AMOR-PERFEITO");
        labelWord2.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        buttonReturn.setBackground(new java.awt.Color(102, 102, 102));
        buttonReturn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/resources/return.png"))); // NOI18N
        buttonReturn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        buttonReturn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonReturnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(buttonWord3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(labelWord3, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(buttonWord1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(labelWord1, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(buttonWord2)
                                .addGap(37, 37, 37)
                                .addComponent(labelWord2, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(buttonReturn, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                .addComponent(labelImage, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelImage, javax.swing.GroupLayout.DEFAULT_SIZE, 524, Short.MAX_VALUE)
                .addGap(31, 31, 31))
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(buttonReturn, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(buttonWord1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(labelWord1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(labelWord2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonWord2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(buttonWord3, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(labelWord3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40))
        );

        setBounds(0, 0, 1255, 596);
    }// </editor-fold>//GEN-END:initComponents

    private void buttonReturnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonReturnActionPerformed
        this.setVisible(false);
        this.mainWindow.getDesktop().add(this.mainWindow.getMv().getAv());
        adjustButtons();
    }//GEN-LAST:event_buttonReturnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonReturn;
    private javax.swing.JButton buttonWord1;
    private javax.swing.JButton buttonWord2;
    private javax.swing.JButton buttonWord3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel labelImage;
    private javax.swing.JLabel labelWord1;
    private javax.swing.JLabel labelWord2;
    private javax.swing.JLabel labelWord3;
    // End of variables declaration//GEN-END:variables
}
