/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.applet.Applet;
import java.applet.AudioClip;
import java.net.URL;
import javax.swing.JDesktopPane;


/**
 *
 * @author gabrielstahlberg
 */
public class StartView extends javax.swing.JInternalFrame {
     MainWindow mainWindow;
     AudioClip sound;
    /**
     * Creates new form MenuView
     */
    public StartView(MainWindow m) {
        initComponents();
        this.mainWindow = m;
        startSound();
        
        
    }
 
    /**
     * EXECUTA UMA MÚSICA
     */
    private void startSound(){
        URL som = MainWindow.class.getResource("resources/startSound.wav");
        this.sound = Applet.newAudioClip(som);
        this.sound.loop();
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        buttonPlay = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setMaximizable(true);
        setResizable(true);
        setPreferredSize(new java.awt.Dimension(750, 600));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/resources/alfabetizacao-e-letramento.jpg"))); // NOI18N

        buttonPlay.setBackground(new java.awt.Color(77, 153, 57));
        buttonPlay.setFont(new java.awt.Font("Noto Sans", 1, 36)); // NOI18N
        buttonPlay.setForeground(new java.awt.Color(253, 251, 251));
        buttonPlay.setText("JOGAR");
        buttonPlay.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        buttonPlay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonPlayActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Manjari Regular", 3, 30)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(53, 44, 200));
        jLabel2.setText("JOGOS EDUCATIVOS");

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/resources/letra-imagem-animada-1143.gif"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(60, 60, 60)
                            .addComponent(jLabel1))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(60, 60, 60)
                            .addComponent(jLabel3))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(45, 45, 45)
                            .addComponent(jLabel4)
                            .addGap(185, 185, 185)
                            .addComponent(buttonPlay, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(69, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(8, 8, 8))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(buttonPlay, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        setBounds(0, 0, 750, 600);
    }// </editor-fold>//GEN-END:initComponents

    private void buttonPlayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonPlayActionPerformed
        this.mainWindow.getDesktop().removeAll();
        this.sound.stop();
        mainWindow.getButtonHome().setEnabled(true);
        MenuView mv = new MenuView(this.mainWindow);
        mv.setVisible(true);
        this.mainWindow.getDesktop().add(mv);                
    }//GEN-LAST:event_buttonPlayActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonPlay;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
}
