/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.applet.Applet;
import java.applet.AudioClip;
import java.net.URL;
import javax.swing.JDesktopPane;


/**
 *
 * @author gabrielstahlberg
 */
public class StartView extends javax.swing.JInternalFrame {
     MainWindow mainWindow;
     AudioClip sound;
     MenuView mv;
    /**
     * Creates new form MenuView
     */
    public StartView(MainWindow m) {
        initComponents();
        this.mainWindow = m;
        //startSound();
    }
 
    /**
     * EXECUTA UMA MÚSICA
     */
    private void startSound(){
        URL som = MainWindow.class.getResource("resources/startSound.wav");
        this.sound = Applet.newAudioClip(som);
        this.sound.loop();
    }

    public MenuView getMv() {
        return mv;
    }

    public void setMv(MenuView mv) {
        this.mv = mv;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonPlay = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setMaximizable(true);
        setResizable(true);
        setPreferredSize(new java.awt.Dimension(750, 600));

        buttonPlay.setBackground(new java.awt.Color(77, 153, 57));
        buttonPlay.setFont(new java.awt.Font("Noto Sans", 1, 36)); // NOI18N
        buttonPlay.setForeground(new java.awt.Color(253, 251, 251));
        buttonPlay.setText("JOGAR");
        buttonPlay.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        buttonPlay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonPlayActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Manjari Regular", 3, 30)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(53, 44, 200));
        jLabel2.setText("JOGOS EDUCATIVOS");

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/resources/letra-imagem-animada-1143.gif"))); // NOI18N

        jLabel1.setText("jLabel1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGap(45, 45, 45)
                            .addComponent(jLabel4))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(60, 60, 60)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel2)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel3)
                                    .addGap(386, 386, 386)
                                    .addComponent(buttonPlay, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(512, 512, 512)
                        .addComponent(jLabel1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(125, 125, 125)
                .addComponent(jLabel1)
                .addGap(226, 226, 226)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3)
                    .addComponent(buttonPlay, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        setBounds(0, 0, 1255, 596);
    }// </editor-fold>//GEN-END:initComponents

    private void buttonPlayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonPlayActionPerformed
        this.mainWindow.getDesktop().removeAll();
        //this.sound.stop();
        mainWindow.getButtonHome().setEnabled(true);
        mv = new MenuView(this.mainWindow);
        mv.setVisible(true);
        this.mainWindow.getDesktop().add(mv);                
    }//GEN-LAST:event_buttonPlayActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonPlay;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
}
